<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="969" started-at="2018-03-02T16:55:16Z" finished-at="2018-03-02T16:55:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="969" started-at="2018-03-02T16:55:16Z" finished-at="2018-03-02T16:55:17Z">
      <class name="com.eaynotes.serviceTest.NoteServiceUnitTest">
        <test-method status="PASS" signature="initMock()[pri:0, instance:com.eaynotes.serviceTest.NoteServiceUnitTest@13805618]" name="initMock" is-config="true" duration-ms="750" started-at="2018-03-02T16:55:16Z" finished-at="2018-03-02T16:55:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initMock -->
        <test-method status="PASS" signature="NSUT1_createNote_TitleNotFound(com.easynotes.dto.NoteInDto)[pri:0, instance:com.eaynotes.serviceTest.NoteServiceUnitTest@13805618]" name="NSUT1_createNote_TitleNotFound" duration-ms="109" started-at="2018-03-02T16:55:17Z" data-provider="getNoteInDto" finished-at="2018-03-02T16:55:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.easynotes.dto.NoteInDto@197d671]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NSUT1_createNote_TitleNotFound -->
        <test-method status="PASS" signature="initMock()[pri:0, instance:com.eaynotes.serviceTest.NoteServiceUnitTest@13805618]" name="initMock" is-config="true" duration-ms="0" started-at="2018-03-02T16:55:17Z" finished-at="2018-03-02T16:55:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initMock -->
        <test-method status="FAIL" signature="NSUT2_CreateNote_Success(com.easynotes.dto.NoteInDto, com.easynotes.model.NoteEntity)[pri:0, instance:com.eaynotes.serviceTest.NoteServiceUnitTest@13805618]" name="NSUT2_CreateNote_Success" duration-ms="16" started-at="2018-03-02T16:55:17Z" data-provider="getNoteInDtoAndNoteEntityData" finished-at="2018-03-02T16:55:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.easynotes.dto.NoteInDto@124c278f]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.easynotes.model.NoteEntity@15b204a1]]>
              </value>
            </param>
          </params>
          <exception class="com.easynotes.exception.DataNotFoundException">
            <message>
              <![CDATA[NOT_FOUND]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.easynotes.exception.DataNotFoundException: NOT_FOUND
at com.easynotes.serviceImpl.NoteServiceImpl.createNote(NoteServiceImpl.java:37)
at com.eaynotes.serviceTest.NoteServiceUnitTest.NSUT2_CreateNote_Success(NoteServiceUnitTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.easynotes.exception.DataNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NSUT2_CreateNote_Success -->
      </class> <!-- com.eaynotes.serviceTest.NoteServiceUnitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
